const INSERT_POST_QUERY = 'INSERT INTO FacebookPosts(VendorID,PostDate,Contents) VALUES(?,?,?)';
const INSERT_DURIANPRICE_QUERY = 'INSERT INTO DurianPrices(VendorID,PostDate,DurianTypeID,PricePerKilo) VALUES(?,?,?,?)';
const SELECT_ALL_QUERY = 'SELECT * FROM ?? ';
const WHERE_VENDORID_CONDITION = 'WHERE VendorID=? ';
const SELECT_VENDORID_BY_FBPAGENAME_QUERY = 'SELECT VendorID FROM Vendors WHERE FacebookPageName=?';
// const SELECT_PROCESSED_POSTID_QUERY = 'SELECT VendorID,PostDate FROM DurianPrices GROUP BY VendorID,PostDate';
const SELECT_UNPROCESSED_FBPOSTS_QUERY = 'SELECT * FROM FacebookPosts WHERE IsProcessed IS NOT TRUE';

module.exports.INSERT_POST_QUERY=INSERT_POST_QUERY;
module.exports.INSERT_DURIANPRICE_QUERY=INSERT_DURIANPRICE_QUERY;
module.exports.SELECT_ALL_QUERY=SELECT_ALL_QUERY;
module.exports.WHERE_VENDORID_CONDITION=WHERE_VENDORID_CONDITION;
module.exports.SELECT_VENDORID_BY_FBPAGENAME_QUERY=SELECT_VENDORID_BY_FBPAGENAME_QUERY;
// module.exports.SELECT_PROCESSED_POSTID_QUERY=SELECT_PROCESSED_POSTID_QUERY;
module.exports.SELECT_UNPROCESSED_FBPOSTS_QUERY=SELECT_UNPROCESSED_FBPOSTS_QUERY;