const INSERT_POST_QUERY = 'INSERT INTO FacebookPosts(VendorID,PostDate,Contents) VALUES(?,?,?)';
const SELECT_ALL_QUERY = 'SELECT * FROM ?? ';
const WHERE_VENDORID_CONDITION = 'WHERE VendorID=? ';
const SELECT_VENDORID_BY_FBPAGENAME_QUERY = 'SELECT VendorID FROM Vendors WHERE FacebookPageName=?';

module.exports.INSERT_POST_QUERY=INSERT_POST_QUERY;
module.exports.SELECT_ALL_QUERY=SELECT_ALL_QUERY;
module.exports.WHERE_VENDORID_CONDITION=WHERE_VENDORID_CONDITION;
module.exports.SELECT_VENDORID_BY_FBPAGENAME_QUERY=SELECT_VENDORID_BY_FBPAGENAME_QUERY;